config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'
  resources :publics do
    resources :posts
    resources :public_users
  end
  resources :posts do
    resources :likes
    resources :dislikes
    resources :comments
  end
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'users/show'
  resources :users, :only => [:show]
  match 'users/:id', to: 'users#destroy', via: :delete
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :public
  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :image, dependent: :destroy

  validates_presence_of :title
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @user_likes = Like.where(user_id: current_user.id)
    @comment = Comment.new(post_id: @post.id)
  end

  # GET /posts/new
  def new
    @post = Post.new
    @public = Public.find(params[:public_id])
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.fetch(:post, {}).permit(:title, :text, :youtube_link, :image, :public_id, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments.html.erb
<% if post.comments.present? %>
  <% post.comments.each do |comment| %>
    <div class="comment">
      <p><a href="<% user_path(comment.user) %>"><b><%= comment.user.name %></b></a></p>
      <p><%= comment.text %></p>
    </div>
  <% end %>
<% end %>
  
<%= form_with(model: [ post, post.comments.build ]) do |f| %>

  <div class="Polaris-FormLayout">
    <div class="Polaris-FormLayout__Item">
      <div class="">
        <div class="Polaris-Labelled__LabelWrapper">
          <div class="Polaris-Label">
            <%= f.label :text, class: 'Polaris-Label__Text' %>
          </div>
        </div>
        <div class="Polaris-Connected">
          <div class="Polaris-Connected__Item Polaris-Connected__Item--primary">
            <div class="Polaris-TextField">
              <%= f.text_area :text, autofocus: true, class: 'Polaris-TextField__Input' %>
              <div class="Polaris-TextField__Backdrop"></div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <%= f.hidden_field :post_id, value: post.id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <button class="Polaris-Button Polaris-Button--primary" type="submit">
    <span class="Polaris-Button__Content">
      <span class="Polaris-Button__Text">
        Comment
      </span>
    </span>
  </button>
<% end %>

app/views/posts/_form.html.erb
<div class="custom-narrow_container">
  <h2 class="custom-page_title">New post in <a href="<%= public_path(@public) %>"><%= @public.name %></a></h2>

  <%= form_with(model: post, local: true) do |f| %>

    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="Polaris-FormLayout">
      <div class="Polaris-FormLayout__Item">
        <div class="">
          <div class="Polaris-Labelled__LabelWrapper">
            <div class="Polaris-Label">
              <%= f.label :title, class: 'Polaris-Label__Text' %>
            </div>
          </div>
          <div class="Polaris-Connected">
            <div class="Polaris-Connected__Item Polaris-Connected__Item--primary">
              <div class="Polaris-TextField">
                <%= f.text_field :title, autofocus: true, class: 'Polaris-TextField__Input' %>
                <div class="Polaris-TextField__Backdrop"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="Polaris-FormLayout__Item">
        <div class="">
          <div class="Polaris-Labelled__LabelWrapper">
            <div class="Polaris-Label">
            <%= f.label :text, 'Caption (Optional)', class: 'Polaris-Label__Text' %>
            </div>
          </div>
          <div class="Polaris-Connected">
            <div class="Polaris-Connected__Item Polaris-Connected__Item--primary">
              <div class="Polaris-TextField">
                <%= f.text_area :text, class: 'Polaris-TextField__Input' %>
                <div class="Polaris-TextField__Backdrop"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="Polaris-FormLayout__Item">
        <div class="">
          <div class="Polaris-Labelled__LabelWrapper">
            <div class="Polaris-Label">
              <%= f.label :youtube_link, class: 'Polaris-Label__Text' %>
            </div>
          </div>
          <div class="Polaris-Connected">
            <div class="Polaris-Connected__Item Polaris-Connected__Item--primary">
              <div class="Polaris-TextField">
                <%= f.text_field :youtube_link, autofocus: true, class: 'Polaris-TextField__Input' %>
                <div class="Polaris-TextField__Backdrop"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="Polaris-FormLayout__Item">
        <div class="">
          <div class="Polaris-Labelled__LabelWrapper">
            <div class="Polaris-Label">
            <%= f.label 'Image', class: 'Polaris-Label__Text' %>
            </div>
          </div>
          <%= f.file_field :image %>
        </div>
      </div>

      <%= f.hidden_field :public_id, value: @public.id %>
      <%= f.hidden_field :user_id, value: current_user.id %>
    </div>
    <button class="Polaris-Button Polaris-Button--primary" type="submit">
      <span class="Polaris-Button__Content">
        <span class="Polaris-Button__Text">
          Post
        </span>
      </span>
    </button>
  <% end %>
</div>

app/views/posts/_postcard.html.erb
<div class="post-container">
  <div class="post-header">
    <div class="post-title">
      <a href="<%= post_path(post) %>" style="color: white;"><%= post.title %></a>
    </div>
    <div class="post-credentials">
      <span class="post-public_title">Posted in <b><a href="<%= public_path(post.public) %>"><%= post.public.name %></a></b></span> by <span class="post-user"><a href="<%= user_path(post.user) %>"><b><%= post.user.name %></b></a> at <%= post.created_at.in_time_zone('Berlin').strftime("%H:%M, %d.%m.%y") %></span>
    </div>
  </div>
  <div class="post-content">
    <div class="post-text">
      <%= post.text %>
    </div>
    <div class="post-image">
      <%= image_tag post.image rescue nil %>
    </div>
  </div>
  <div class="post-footer">
    <div class="post-reactions">
      <div class="post-likes">
        <div class="post-like"><b><%= post.likes.count %></b></div>
        <%= button_to post_likes_path(post.id), method: 'post' do %>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path class="<% if Like.find_by(user_id: current_user.id, post_id: post.id).present? %>active<% end %>" d="M14.198 16h-3.896L8 14.465V8.277l2.563-4.273A.502.502 0 0111 4.5V8a1 1 0 001 1h3.753l-1.555 7zm3.582-8.625A1 1 0 0017 7h-4V4.5C13 3.122 11.88 2 10.5 2H10a1 1 0 00-.858.485L6.433 7H3a1 1 0 00-1 1v7a1 1 0 001 1h3.697l2.748 1.832c.164.109.357.168.555.168h5a1 1 0 00.976-.783l2-9a1 1 0 00-.196-.842z" fill="#5C5F62"/></svg>
        <% end %>
      </div>
      <div class="post-dislikes">
        <%= button_to post_dislikes_path(post.id), method: 'post' do %>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path class="<% if Dislike.find_by(user_id: current_user.id, post_id: post.id).present? %>active<% end %>" d="M9.437 15.996A.502.502 0 019 15.5V12a1 1 0 00-1-1H4.248l1.554-7h3.896L12 5.535v6.188l-2.563 4.273zM17 4h-3.697l-2.748-1.832A.995.995 0 0010 2H5c-.468 0-.874.326-.976.783l-2 9A1 1 0 003 13h4v2.5C7 16.878 8.122 18 9.5 18h.5a1 1 0 00.858-.485L13.567 13H17a1 1 0 001-1V5a1 1 0 00-1-1z" fill="#5C5F62"/></svg>
        <% end %>
        <div class="post-dislike"><b><%= post.dislikes.count %></b></div>
      </div>
    </div>
    <div class="post-comment">
      <div class="post-like"><b><%= post.comments.count %></b></div>
      <a href="<%= post_path(post) %>">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M13 10a1 1 0 102 0 1 1 0 00-2 0zm-4 0a1 1 0 102 0 1 1 0 00-2 0zm-4 0a1 1 0 102 0 1 1 0 00-2 0zm5-8c-4.411 0-8 3.589-8 8 0 1.504.425 2.908 1.15 4.111l-1.069 2.495a1 1 0 001.314 1.313l2.494-1.069A7.939 7.939 0 0010 18c4.411 0 8-3.589 8-8s-3.589-8-8-8z" fill="#5C5F62"/></svg>
      </a>
    </div>
    <div class="post-share">
      <a href="#">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M15 12c-.807 0-1.537.324-2.077.844l-4.96-2.481c.015-.12.037-.238.037-.363s-.022-.243-.037-.363l4.96-2.481c.54.52 1.27.844 2.077.844 1.654 0 3-1.346 3-3s-1.346-3-3-3-3 1.346-3 3c0 .125.022.243.037.363l-4.96 2.481A2.986 2.986 0 005 7c-1.654 0-3 1.346-3 3s1.346 3 3 3c.807 0 1.537-.324 2.077-.844l4.96 2.481c-.015.12-.037.238-.037.363 0 1.654 1.346 3 3 3s3-1.346 3-3-1.346-3-3-3z" fill="#5C5F62"/></svg>
      </a>
    </div>
  </div>
</div>

<style>
.post-wrapper .post-text {
  max-height: unset;
}

.post-wrapper .post-container {
  max-height: unset;
  height: auto;
  max-width: 700px;
  width: 700px;
}

.post-wrapper .post-container img {
  all: unset;
  width: 100%;
  height: 100%;
  max-height: 700px;
  object-fit: contain;
}
</style>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="post-wrapper">
  <%= render partial: 'postcard', locals: { post: @post, user_likes: @user_likes } %>
  <%= render partial: 'comments', locals: { post: @post }, object: @comment %>
</div>